image: golang
env:
- GOPATH=/luetbuild/go/
- GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
package_dir: /{{ .Values.name }}
prelude:
- mkdir go/src/github.com/${GITHUB_ORG}/ -p
- cd go/src/github.com/${GITHUB_ORG}/ && git clone https://github.com/${GITHUB_ORG}/{{ .Values.name }}.git
steps:
- >-
  cd go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/ &&
  git checkout v"${PACKAGE_VERSION}" -b build &&
  CGO_ENABLED=0 go build -o {{.Values.name}} ./cmd/{{.Values.name}} &&
  chmod +x {{ .Values.name }} &&
  mkdir /{{ .Values.name }}/usr/bin/ -p &&
  mv {{ .Values.name }} /{{ .Values.name }}/usr/bin/{{ .Values.name }}
