prelude:
- bash copy.sh
env:
- KERNEL_TYPE={{ .Values.prefix }}
- SUFFIX={{ .Values.suffix }}
package_dir: /luetbuild/sources
requires:
- name: "macaroni-lts-full"
  category: "kernel-4.9"
  version: ">=0"
